# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess


class CustomQLineEdit(QtWidgets.QLineEdit):
    def focusInEvent(self, e):
        subprocess.Popen("onboard", shell=True)
        subprocess.call(
            'dbus-send --type=method_call --dest=org.onboard.Onboard /org/onboard/Onboard/Keyboard org.onboard.Onboard.Keyboard.Show',
            shell=True)
        super(CustomQLineEdit, self).focusInEvent(e)

    def focusOutEvent(self, e):
        subprocess.call(
            'dbus-send --type=method_call --dest=org.onboard.Onboard /org/onboard/Onboard/Keyboard org.onboard.Onboard.Keyboard.Hide',
            shell=True)
        subprocess.Popen("pkill onboard", shell=True)
        super(CustomQLineEdit, self).focusOutEvent(e)


class MatchBoxLineEdit(QtWidgets.QLineEdit):
    def focusInEvent(self, e):
        try:
            subprocess.Popen(["matchbox-keyboard"])
        except FileNotFoundError:
            pass

    def focusOutEvent(self, e):
        subprocess.Popen(["killall", "matchbox-keyboard"])
class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        StackedWidget.setObjectName("StackedWidget")
        StackedWidget.resize(1000, 630)
        StackedWidget.setMinimumSize(QtCore.QSize(1000, 630))
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.page)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 100))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.widget_2 = QtWidgets.QWidget(self.page)
        self.widget_2.setObjectName("widget_2")
        self.horizontal_layout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontal_layout.setObjectName("horizontal_layout")
        self.serial_value = QtWidgets.QLineEdit(self.widget_2)
        self.serial_value.setMinimumSize(QtCore.QSize(0, 50))
        self.serial_value.setObjectName("serial_value")
        self.horizontal_layout.addWidget(self.serial_value)
        self.enter = QtWidgets.QPushButton(self.widget_2)
        self.enter.setMinimumSize(QtCore.QSize(150, 150))
        self.enter.setObjectName("enter")
        self.horizontal_layout.addWidget(self.enter)
        self.cancel = QtWidgets.QPushButton(self.widget_2)
        self.cancel.setMinimumSize(QtCore.QSize(150, 150))
        self.cancel.setObjectName("cancel")
        self.horizontal_layout.addWidget(self.cancel)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.textBrowser = QtWidgets.QTextBrowser(self.page)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.widget_1 = QtWidgets.QWidget(self.page)
        self.widget_1.setObjectName("widget_1")
        self.horizontal_layout_2 = QtWidgets.QHBoxLayout(self.widget_1)
        self.horizontal_layout_2.setObjectName("horizontal_layout_2")
        self.deprovision = QtWidgets.QPushButton(self.widget_1)
        self.deprovision.setMinimumSize(QtCore.QSize(0, 100))
        self.deprovision.setObjectName("deprovision")
        self.horizontal_layout_2.addWidget(self.deprovision)
        self.update_serial = QtWidgets.QPushButton(self.widget_1)
        self.update_serial.setMinimumSize(QtCore.QSize(0, 100))
        self.update_serial.setObjectName("update_serial")
        self.horizontal_layout_2.addWidget(self.update_serial)
        self.get_device_info = QtWidgets.QPushButton(self.widget_1)
        self.get_device_info.setMinimumSize(QtCore.QSize(0, 100))
        self.get_device_info.setObjectName("get_device_info")
        self.horizontal_layout_2.addWidget(self.get_device_info)
        self.verticalLayout_2.addWidget(self.widget_1)
        self.sys_label = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(14)
        font.setItalic(True)
        self.sys_label.setFont(font)
        self.sys_label.setText("")
        self.sys_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sys_label.setObjectName("sys_label")
        self.verticalLayout_2.addWidget(self.sys_label, 0, QtCore.Qt.AlignVCenter)
        StackedWidget.addWidget(self.page)

        self.retranslateUi(StackedWidget)
        self.update_serial.clicked.connect(self.widget_2.show)
        self.update_serial.clicked.connect(self.widget_1.hide)
        self.cancel.clicked.connect(self.widget_1.show)
        self.cancel.clicked.connect(self.widget_2.hide)
        self.enter.clicked.connect(self.widget_2.hide)
        self.enter.clicked.connect(self.widget_1.show)
        self.update_serial.clicked.connect(self.serial_value.setFocus)
        QtCore.QMetaObject.connectSlotsByName(StackedWidget)

    def retranslateUi(self, StackedWidget):
        _translate = QtCore.QCoreApplication.translate
        StackedWidget.setWindowTitle(_translate("StackedWidget", "StackedWidget"))
        self.enter.setText(_translate("StackedWidget", "Enter"))
        self.cancel.setText(_translate("StackedWidget", "Cancel"))
        self.deprovision.setText(_translate("StackedWidget", "Deprovision"))
        self.update_serial.setText(_translate("StackedWidget", "Update S/N"))
        self.get_device_info.setText(_translate("StackedWidget", "Get Device Info"))
